# Changes here will be overwritten by Copier
_commit: 2024.11.28
_src_path: gh:zenml-io/template-starter
email: ''
full_name: Paxton Howard
open_source_license: mit
project_name: ZenML Starter
version: 0.1.0
